### ISSUE TITLE
[neutron_multi_image_upload] - limit of the number images

### ISSUE THREAD

**Issue by slowprog** [neutron-project/form-bundle#4]
Can you make a dynamic limit on the number of loaded images? for example

             'configs' => array (
                 'minWidth' => 300,
                 'minHeight' => 100,
                 'extensions' => 'jpeg, jpg',
                 'maxSize' => '2 M ',
                 <b>'maxNumber' => $user->getMaxNumberImage(),</b>
                 'runtimes' => 'html5, flash'
             )

Or some other way, but to each user a their limit.

**Comment by zender** [comment]
you should use symfony count validator: http://symfony.com/doc/current/reference/constraints/Count.html

**Comment by slowprog** [comment]
Hm, I have a dynamic constraint (number of image) that is stored in the database. And I'm more interested in the validation on the client side, not the server side. 

The only thing that occurred to me is to override the event <b>FilesAdded</b>  from <em>multi-image-upload.js</em> in my template.

This is a solution I do not like. You do not have a more elegant solution?

**Comment by zender** [comment]
the only way is to override the <em>multi-image-upload.js</em>.

**Comment by slowprog** [comment]
All right, all right. Thanks for the reply.
