### ISSUE TITLE
[neutron_multi_image_upload] options to don`t store original files

### ISSUE THREAD

**Issue by magician7** [neutron-project/form-bundle#7]
Users store very much images - I don`t need keep original files - I only need image in normalized dimension and thumb only. Is there a option to don`t store original files?

**Comment by zender** [comment]
@magician7 keeping original image is required in order to revert changes. It will not be changed in future.

**Comment by magician7** [comment]
@zender - make it possible to block revert changes and take option to don't store original files to save space will be too complicated to implement?

**Comment by zender** [comment]
Cropping and resetting need original image . If we disable these features in the configs then original image will not be needed. To achieve that I have to modify the code. If you have better idea just fork the source.

**Comment by magician7** [comment]
A this moment - no. I'm new in Symfony2 and at this moment I'm learn how it`s works... And for my point of view code modification is needed.
