### ISSUE TITLE
[neutron_multi_file_upload] Some MIME-types don't working

### ISSUE THREAD

**Issue by slowprog** [neutron-project/form-bundle#8]
In the creation of the form added extensions:

<pre>'configs' => array(
    'extensions' => 'application/pdf, application/dxf, application/dwg, application/acad, application/x-acad, application/autocad_dwg, image/x-dwg, application/dwg, application/x-dwg, application/x-autocad, image/vnd.dwg, drawing/dwg',
    ...
)</pre>

I tried to upload the files .dwg of AutoCAD (http://ru.wikipedia.org/wiki/DWG). But showed error:

<pre>asd.dwg: The mime type of the file is invalid ("application/octet-stream"). <br/>Allowed mime types are "application/pdf", "application/dxf", "application/dwg", <br/>"application/acad", "application/x-acad", "application/autocad_dwg", <br/>"image/x-dwg", "application/dwg", "application/x-dwg", "application/x-autocad", <br/>"image/vnd.dwg", "drawing/dwg".</pre>

also for type .dxf.

<pre>... The mime type of the file is invalid ("text/plain"). Allowed mime types are ...</pre>

Works only type .pdf. Even if I will add MIME-types from errors (application/octet-stream and text/plain) in the extensions, then it still will not work. Maybe I am doing something wrong? Tell me, please.

**Comment by zender** [comment]
Try without whitespace: "application/pdf,application/zip". It works for me.
Also check: http://www.iana.org/assignments/media-types

**Comment by slowprog** [comment]
You right! Without whitespace is working. I'm stupid. And thanx for link, it explains a lot:

<pre>
Any entity with an unrecognized Content-Transfer-Encoding must be treated as if it has a Content-Type of "application/octet-stream", regardless of what the Content-Type header field actually says.
...
The "octet-stream" subtype is used to indicate that a body contains arbitrary binary data.</pre>

I did not know that. now I know
